# syntax=docker/dockerfile:1
ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION} AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ---------------------------------------------------------------------------
# EVERY NEXT_PUBLIC_ VALUE MUST BE DECLARED HERE
# ---------------------------------------------------------------------------
# These are inlined into the JavaScript bundle during `npm run build`, so they
# have to be present as build args — a runtime environment variable is far too
# late. docker-compose supplies them from the single root .env.
#
# A missing one is not silent: src/config/site.ts throws with the variable's
# name and the build fails. That is deliberate. The alternative is an image
# that builds cleanly and serves someone else's phone number.
#
# Adding a NEXT_PUBLIC_ variable means adding it in THREE places: .env.example,
# the `args:` block in docker-compose.yml, and here.
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_ALLOW_INDEXING
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_COMPANY_NAME
ARG NEXT_PUBLIC_COMPANY_TAGLINE
ARG NEXT_PUBLIC_COMPANY_DESCRIPTION
ARG NEXT_PUBLIC_COMPANY_STRAPLINE
ARG NEXT_PUBLIC_COMPANY_AREA_SERVED
ARG NEXT_PUBLIC_CONTACT_PHONE
ARG NEXT_PUBLIC_CONTACT_PHONE_E164
ARG NEXT_PUBLIC_CONTACT_EMAIL
ARG NEXT_PUBLIC_ADDRESS_STREET
ARG NEXT_PUBLIC_ADDRESS_LOCALITY
ARG NEXT_PUBLIC_ADDRESS_REGION
ARG NEXT_PUBLIC_ADDRESS_COUNTRY
ARG NEXT_PUBLIC_ADDRESS_COUNTRY_CODE
ARG NEXT_PUBLIC_OPENING_HOURS
ARG NEXT_PUBLIC_SOCIAL_FACEBOOK
ARG NEXT_PUBLIC_SOCIAL_INSTAGRAM
ARG NEXT_PUBLIC_SOCIAL_LINKEDIN
ARG NEXT_PUBLIC_BRAND_THEME_COLOR
ARG NEXT_PUBLIC_BRAND_ON_DARK_COLOR
ARG NEXT_PUBLIC_BRAND_BACKGROUND_COLOR
ARG NEXT_PUBLIC_BRAND_LOGO
ARG NEXT_PUBLIC_BRAND_LOGO_INVERSE
ARG NEXT_PUBLIC_BRAND_LOGO_WIDTH
ARG NEXT_PUBLIC_BRAND_LOGO_HEIGHT
ARG NEXT_PUBLIC_SITE_LOCALE
ARG NEXT_PUBLIC_SITE_LANGUAGE

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_ALLOW_INDEXING=$NEXT_PUBLIC_ALLOW_INDEXING \
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME \
    NEXT_PUBLIC_COMPANY_NAME=$NEXT_PUBLIC_COMPANY_NAME \
    NEXT_PUBLIC_COMPANY_TAGLINE=$NEXT_PUBLIC_COMPANY_TAGLINE \
    NEXT_PUBLIC_COMPANY_DESCRIPTION=$NEXT_PUBLIC_COMPANY_DESCRIPTION \
    NEXT_PUBLIC_COMPANY_STRAPLINE=$NEXT_PUBLIC_COMPANY_STRAPLINE \
    NEXT_PUBLIC_COMPANY_AREA_SERVED=$NEXT_PUBLIC_COMPANY_AREA_SERVED \
    NEXT_PUBLIC_CONTACT_PHONE=$NEXT_PUBLIC_CONTACT_PHONE \
    NEXT_PUBLIC_CONTACT_PHONE_E164=$NEXT_PUBLIC_CONTACT_PHONE_E164 \
    NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL \
    NEXT_PUBLIC_ADDRESS_STREET=$NEXT_PUBLIC_ADDRESS_STREET \
    NEXT_PUBLIC_ADDRESS_LOCALITY=$NEXT_PUBLIC_ADDRESS_LOCALITY \
    NEXT_PUBLIC_ADDRESS_REGION=$NEXT_PUBLIC_ADDRESS_REGION \
    NEXT_PUBLIC_ADDRESS_COUNTRY=$NEXT_PUBLIC_ADDRESS_COUNTRY \
    NEXT_PUBLIC_ADDRESS_COUNTRY_CODE=$NEXT_PUBLIC_ADDRESS_COUNTRY_CODE \
    NEXT_PUBLIC_OPENING_HOURS=$NEXT_PUBLIC_OPENING_HOURS \
    NEXT_PUBLIC_SOCIAL_FACEBOOK=$NEXT_PUBLIC_SOCIAL_FACEBOOK \
    NEXT_PUBLIC_SOCIAL_INSTAGRAM=$NEXT_PUBLIC_SOCIAL_INSTAGRAM \
    NEXT_PUBLIC_SOCIAL_LINKEDIN=$NEXT_PUBLIC_SOCIAL_LINKEDIN \
    NEXT_PUBLIC_BRAND_THEME_COLOR=$NEXT_PUBLIC_BRAND_THEME_COLOR \
    NEXT_PUBLIC_BRAND_ON_DARK_COLOR=$NEXT_PUBLIC_BRAND_ON_DARK_COLOR \
    NEXT_PUBLIC_BRAND_BACKGROUND_COLOR=$NEXT_PUBLIC_BRAND_BACKGROUND_COLOR \
    NEXT_PUBLIC_BRAND_LOGO=$NEXT_PUBLIC_BRAND_LOGO \
    NEXT_PUBLIC_BRAND_LOGO_INVERSE=$NEXT_PUBLIC_BRAND_LOGO_INVERSE \
    NEXT_PUBLIC_BRAND_LOGO_WIDTH=$NEXT_PUBLIC_BRAND_LOGO_WIDTH \
    NEXT_PUBLIC_BRAND_LOGO_HEIGHT=$NEXT_PUBLIC_BRAND_LOGO_HEIGHT \
    NEXT_PUBLIC_SITE_LOCALE=$NEXT_PUBLIC_SITE_LOCALE \
    NEXT_PUBLIC_SITE_LANGUAGE=$NEXT_PUBLIC_SITE_LANGUAGE \
    NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup -S nodejs && adduser -S nextjs -G nodejs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
