# Generated by Django 5.2.17 on 2026-08-21 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('media_alt', models.CharField(blank=True, max_length=255)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'formats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'db_table': 'industries',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, help_text='catalogue | pricelist | website | statement | supplier', max_length=40)),
                ('revision', models.CharField(blank=True, help_text='e.g. "Q3 2026". Blank if unversioned.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_documents',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('media_alt', models.CharField(blank=True, max_length=255)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalogue.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.application')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.category')),
            ],
            options={
                'db_table': 'application_categories',
                'ordering': ['position'],
                'unique_together': {('application', 'category')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='applications', through='catalogue.ApplicationCategory', to='catalogue.category'),
        ),
        migrations.AddField(
            model_name='application',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='catalogue.industry'),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_id', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Set when the asset was ingested from a URL rather than uploaded.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalogue.mediaasset'),
        ),
        migrations.AddField(
            model_name='application',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='catalogue.mediaasset'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('benefit', models.TextField(blank=True)),
                ('olfactive', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('authoritative', 'Authoritative — verbatim from a Cerium document'), ('human_approved', 'Human approved'), ('ai_draft', 'AI draft — not published'), ('ai_suggestion', 'AI suggestion — needs review')], default='ai_draft', max_length=20)),
                ('published', models.BooleanField(default=False, help_text='Unpublished products are absent from the site and the sitemap.')),
                ('media_alt', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Longer editorial copy. May be AI-drafted, but it is published only once a human has reviewed it and moved status off ai_draft.')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.category')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.mediaasset')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.format')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'db_table': 'product_formats',
                'ordering': ['position'],
                'unique_together': {('product', 'format')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalogue.ProductFormat', to='catalogue.format'),
        ),
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('slot', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_slots', to='catalogue.mediaasset')),
            ],
            options={
                'verbose_name_plural': 'site media',
                'db_table': 'site_media',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.sourcedocument'),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalogue.sourcedocument'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['published', 'category'], name='products_publish_8fd5b1_idx'),
        ),
    ]
